export const sheetSchemas: Record<string, string[]> = {
  stories: [
    "id",
    "title",
    "theme",
    "world",
    "mapIds",
    "characters",
    "monsters",
    "objectIds",
    "castDocFactions",
    "castDocRules",
    "castDocEvents",
    "castDocGoals",
    "systems",
    "plotSequences",
    "beats"
  ],
  maps: ["id", "name", "recommendedPower", "monsterIds", "scriptLocationName", "scriptDefaultIntExt", "scriptDefaultTimeOfDay"],
  characters: [
    "id",
    "screenplayCueName",
    "tmdbPersonId",
    "tmdbGender",
    "imdbId",
    "homepage",
    "name",
    "description",
    "appearance",
    "personality",
    "generationPrompt",
    "rarity",
    "className",
    "nation",
    "element",
    "str",
    "agi",
    "luk",
    "intel",
    "atk",
    "hp",
    "skillIds",
    "maxPages",
    "storyPages"
  ],
  monsters: ["id", "screenplayCueName", "name", "rarity", "element", "str", "agi", "luk", "intel", "atk", "hp", "skillIds"],
  storyBranches: [
    "id",
    "chapter",
    "title",
    "eventType",
    "eventTier",
    "rewardHint",
    "riskHint",
    "event",
    "optionA",
    "optionB",
    "optionC",
    "flagA",
    "flagB",
    "flagC"
  ],
  skills: ["id", "name", "description", "powerMultiplier", "cooldown", "kind"],
  weapons: ["id", "name", "slot", "rarity", "skillIds", "atk", "hp"],
  items: ["id", "name", "type", "effect", "amount"],
  equipments: ["id", "name", "slot", "rarity", "skillIds", "atk", "hp"]
};

